name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 1 # Ethereum Mainnet
    start_block: 19761922 # not the beginning of time, just for local testing
    contracts:
      - name: ERC20
        address: "0xdAC17F958D2ee523a2206206994597C13D831ec7" #usdt mainnet
        handler: src/EventHandlers.ts
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
